file1 = open("test1.txt")
print(file1.read())
file1.seek(0)
print(file1.read())
file1.seek(0)
print(file1.read())
file1.close()

file2 = open("test2.txt")
# print(file2.readline())
# print(file2.readline())
# print(file2.readline())
print(file2.readlines())
file2.close()
